"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.NoPathsMatch = exports.AllPathsMatch = exports.MustNotBeEmpty = exports.MustBeDirectory = void 0;
const getPaths = (files) => (Array.from(files).map(file => file.webkitRelativePath));
const MustBeDirectory = (files) => (Array.from(files).every(path => !!path));
exports.MustBeDirectory = MustBeDirectory;
const MustNotBeEmpty = (files) => files.length > 0;
exports.MustNotBeEmpty = MustNotBeEmpty;
exports.AllPathsMatch = 0;
exports.NoPathsMatch = 0;
